<?php

/**
 * @file
 * Provides a home api metrics entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function home_api_metrics_theme() {
  return [
    'home_api_metrics' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for home api metrics templates.
 *
 * Default template: home-api-metrics.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the home api metrics information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_home_api_metrics(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
